import os

TELEGRAM_TOKEN = os.getenv("TELEGRAM_TOKEN")
TELEGRAM_CHAT_ID = os.getenv("TELEGRAM_CHAT_ID")

SHOPEE_AFFILIATE_ID = os.getenv("SHOPEE_AFFILIATE_ID")
ML_AFFILIATE_ID = os.getenv("ML_AFFILIATE_ID")
